### ISSUE TITLE
ValueError: Cannot feed value of shape (100, 11, 11, 11) for Tensor u'x:0', which has shape '(?, 12, 11, 11)'

### ISSUE THREAD

**Issue by emirceyani** [vyokky/Mobihoc-18-STN-mobile-traffic-forecasting#1]
Hello,

First of all, I preprocessed the dataset as you stated in both issues of https://github.com/vyokky/ZipNet-GAN-traffic-inference/issues and for milan dataset\ the shapes for splits are given as 

('training set:', (100, 100, 5952))
('validation set:', (100, 100, 1488))
('test set:', (100, 100, 1488))
Numbers are according to the paper and it is correct.
(I can share the ipynb for the preprocessing to check if u wish)
Second, stn-train.py and LayerExtension contains some minor bugs:

For stn-train there`s don't use tl.layers.identity at the final Dense layer. Just use tf.identity

For the LayerExtension\ when using init, you need to specify the previous layer as in the gist: https://gist.github.com/emirceyani/377c6be7fe4dac5e0d9dd17f9b6f4a2b

So, after that I got the following error without specifying any terminal arguments(just to check):

 python stn-train.py
2019-03-30 17:57:32.257934: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-03-30 17:57:32.278594: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
2019-03-30 17:57:32.279987: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x559769a985a0 executing computations on platform Host. Devices:
2019-03-30 17:57:32.280033: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
('training set:', (100, 100, 5952))
('validation set:', (100, 100, 1488))
('test set:', (100, 100, 1488))
WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
  tensorlayer:Instantiate RNNLayer stn/convlstm1: feature_map:3, n_steps:12, in_dim:5 (?, 12, 11, 11, 1), cell_fn:BasicConvLSTMCell 
     non specified batch_size, uses a tensor instead.
 n_params : 2
  tensorlayer:Instantiate RNNLayer stn/convlstm2: feature_map:6, n_steps:12, in_dim:5 (?, 12, 11, 11, 6), cell_fn:BasicConvLSTMCell 
     non specified batch_size, uses a tensor instead.
 n_params : 2
  tensorlayer:Instantiate RNNLayer stn/convlstm3: feature_map:12, n_steps:12, in_dim:5 (?, 12, 11, 11, 12), cell_fn:BasicConvLSTMCell 
     non specified batch_size, uses a tensor instead.
 n_params : 2
WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
set done
Start training the network ...
Traceback (most recent call last):
  File "stn-train.py", line 221, in <module>
    save_path=args.model_path + args.model_name, epoch_identifier=None)
  File "/home/deepsorcerer/Desktop/mobihoc-18-stn-mobile-traffic-forecasting/toolbox/NetFlow.py", line 91, in customfit
    loss, _ = sess.run([cost, train_op], feed_dict=feed_dict)
  File "/home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 11, 11, 11) for Tensor u'x:0', which has shape '(?, 12, 11, 11)'

Also, if you have time, could you please explain the dataset preprocessing and a better readme for both stn and zipnetgan for reproducing them?

Thanks

**Comment by vyokky** [comment]
Hi,

This is a small bug and now has been fixed. Please try again.

**Comment by saloni103** [comment]
Is it possible to get the clean or processed data set used to train the model ?

Thanks

**Comment by xuxunima** [comment]
> Hello,
> 
> First of all, I preprocessed the dataset as you stated in both issues of https://github.com/vyokky/ZipNet-GAN-traffic-inference/issues and for milan dataset\ the shapes for splits are given as
> 
> ('training set:', (100, 100, 5952))
> ('validation set:', (100, 100, 1488))
> ('test set:', (100, 100, 1488))
> Numbers are according to the paper and it is correct.
> (I can share the ipynb for the preprocessing to check if u wish)
> Second, stn-train.py and LayerExtension contains some minor bugs:
> 
> For stn-train there`s don't use tl.layers.identity at the final Dense layer. Just use tf.identity
> 
> For the LayerExtension\ when using init, you need to specify the previous layer as in the gist: https://gist.github.com/emirceyani/377c6be7fe4dac5e0d9dd17f9b6f4a2b
> 
> So, after that I got the following error without specifying any terminal arguments(just to check):
> 
>  python stn-train.py
> 2019-03-30 17:57:32.257934: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> 2019-03-30 17:57:32.278594: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
> 2019-03-30 17:57:32.279987: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x559769a985a0 executing computations on platform Host. Devices:
> 2019-03-30 17:57:32.280033: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): ,
> ('training set:', (100, 100, 5952))
> ('validation set:', (100, 100, 1488))
> ('test set:', (100, 100, 1488))
> WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> tensorlayer:Instantiate RNNLayer stn/convlstm1: feature_map:3, n_steps:12, in_dim:5 (?, 12, 11, 11, 1), cell_fn:BasicConvLSTMCell
> non specified batch_size, uses a tensor instead.
> n_params : 2
> tensorlayer:Instantiate RNNLayer stn/convlstm2: feature_map:6, n_steps:12, in_dim:5 (?, 12, 11, 11, 6), cell_fn:BasicConvLSTMCell
> non specified batch_size, uses a tensor instead.
> n_params : 2
> tensorlayer:Instantiate RNNLayer stn/convlstm3: feature_map:12, n_steps:12, in_dim:5 (?, 12, 11, 11, 12), cell_fn:BasicConvLSTMCell
> non specified batch_size, uses a tensor instead.
> n_params : 2
> WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> WARNING:tensorflow:From /home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:193: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
> Instructions for updating:
> Use `tf.global_variables_initializer` instead.
> set done
> Start training the network ...
> Traceback (most recent call last):
> File "stn-train.py", line 221, in
> save_path=args.model_path + args.model_name, epoch_identifier=None)
> File "/home/deepsorcerer/Desktop/mobihoc-18-stn-mobile-traffic-forecasting/toolbox/NetFlow.py", line 91, in customfit
> loss, _ = sess.run([cost, train_op], feed_dict=feed_dict)
> File "/home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
> run_metadata_ptr)
> File "/home/deepsorcerer/anaconda3/envs/patras/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
> str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (100, 11, 11, 11) for Tensor u'x:0', which has shape '(?, 12, 11, 11)'
> 
> Also, if you have time, could you please explain the dataset preprocessing and a better readme for both stn and zipnetgan for reproducing them?
> 
> Thanks

**Comment by xuxunima** [comment]
Hello,
Could you please send me the processed data or the ipynb ?
 My email : xujialu801516@163.com

Thanks

**Comment by emirceyani** [comment]
Here's a pdf version of my .ipynb.

[data_process.pdf](https://github.com/vyokky/Mobihoc-18-STN-mobile-traffic-forecasting/files/4215648/data_process.pdf)

If anything happens, continue the thread or mail me(emirceyani@gmail.com)

**Comment by xuxunima** [comment]
> Here's a pdf version of my .ipynb.
> 
> [data_process.pdf](https://github.com/vyokky/Mobihoc-18-STN-mobile-traffic-forecasting/files/4215648/data_process.pdf)
> 
> If anything happens, continue the thread or mail me([emirceyani@gmail.com](mailto:emirceyani@gmail.com))

**Comment by xuxunima** [comment]
@emirceyani 
Thanks, It really helped me a lot!
